#!/usr/bin/env python3
"""mkstill.py - build temporal test masters from a short real master.

The corpus masters are 2-3 frames, which is too thin for a temporal metric.
Two constructions, both from real footage, neither inventing pixel content:

  still  <n>   frame 0 repeated n times.  The source's frame-to-frame movement
               is EXACTLY zero, so any movement in the decode is generated by
               the codec and nothing else.  This is the sharpest possible form
               of "match the source": the source is perfectly still, so the
               target is perfectly still.
  loop   <n>   the frames walked forward and back (0,1,2,1,0,...) to n frames.
               Real content motion with a real source movement level, for
               checking that a fix has not simply removed texture.

  mkstill.py <in.yuv> <out.yuv> <W> <H> <422|444> <depth> <still|loop> <n>
"""
import sys, numpy as np
src, dst, W, H, fmt, depth, mode, n = (sys.argv[1], sys.argv[2], int(sys.argv[3]),
    int(sys.argv[4]), sys.argv[5], int(sys.argv[6]), sys.argv[7], int(sys.argv[8]))
Wc = W if fmt == '444' else W // 2
fw = W * H + 2 * Wc * H
a = np.fromfile(src, dtype='<u2')
assert a.size % fw == 0, "not a whole number of frames at this geometry"
a = a.reshape(-1, fw)
nf = a.shape[0]
if mode == 'still':
    idx = [0] * n
else:
    seq = list(range(nf)) + list(range(nf - 2, 0, -1))
    idx = [seq[i % len(seq)] for i in range(n)]
a[idx].tofile(dst)
print("wrote %s: %d frames, %s, from %d source frame(s)" % (dst, n, mode, nf))
