/* Generated by harness/train_tables2.py - OMC v2 normative tANS table groups */
#ifndef OMC1_TABLES_H
#define OMC1_TABLES_H
#include <stdint.h>
#define OMC_TANS_L 1024
#define OMC_TANS_LBITS 10
#define OMC_NSYM 16
/* v4.4 normative entropy model: 16 magnitude contexts x 4 table groups
 * (same expanded-table memory as the legacy 4x16; validated held-out).
 * Legacy tables kept for decoding minor <= 3 streams. */
#define OMC_NCTX 16
#define OMC_NTABLES 8
#define OMC_NCTX_V4 OMC_NCTX
#define OMC_NTABLES_V4 OMC_NTABLES
#define OMC_NCTX_LEGACY 4
#define OMC_NTABLES_LEGACY 16
extern const uint16_t omc_tans_counts_legacy[OMC_NTABLES_LEGACY][OMC_NCTX_LEGACY][OMC_NSYM];
extern const uint16_t omc_tans_counts_v4[OMC_NTABLES_V4][OMC_NCTX_V4][OMC_NSYM];
/* Q5F: block-skip-flag contexts (4 block-flag + 4 band-unit).  Separate array so the
 * flag field never borrows a coefficient distribution it does not match. */
#define OMC_NQ5CTX 8
extern const uint16_t omc_tans_counts_q5[OMC_NQ5CTX][OMC_NSYM];
extern const uint16_t omc_tans_cost64_v4[OMC_NTABLES_V4][OMC_NCTX_V4][OMC_NSYM];
#endif
