/* gen_gm_basis.c -- measure the 2-D synthesis basis of every band of the OMC
 * transform and emit src/gm_basis_tab.c.inc.
 *
 * WHY THIS IS MEASURED AND NOT DERIVED.  The in-gamut repair needs to know, for
 * a candidate coefficient and an offending pixel under its support, whether
 * REDUCING that coefficient moves the pixel toward the legal range or further
 * out of it.  That is the sign of the synthesis basis g_k(p), and it must be
 * the sign of the basis the shipping inverse transform actually has, not the
 * sign of the basis somebody believed it had.  So this program runs impulses
 * through omc_slice_inv() itself and reads the answer off the output.  It is
 * built and run by the Makefile, so the table cannot drift from the transform:
 * change a lifting step and the table is regenerated on the next build.
 *
 * WHAT IS TABULATED.  The transform is separable, so the 2-D basis of a
 * coefficient in band k factors as g(j, i) = gy[j] * gx[i].  Both factors are
 * run-length compressed by SIGN, and each run carries the mean |g| over it, so
 * that a rectangle of the picture under one (y-run, x-run) pair has a single
 * signed weight.  That is what makes the repair's test cheap: the score of a
 * candidate coefficient is a weighted sum over at most NY*NX rectangles, and
 * each rectangle is four lookups into a summed-area table of residuals.
 *
 * Build/run:  cc -O2 -Iinclude -o gen_gm_basis repro/gen_gm_basis.c src/dwt.c
 *             ./gen_gm_basis > src/gm_basis_tab.c.inc
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "omc1.h"
#include "../src/internal.h"

#define W  2048
#define SH 32
#define AMP 1048576          /* large, so integer rounding is a rounding error */
#define WQ 1024              /* run weights are Q10 of the band peak */
#define GM_MAXRUN_C 12       /* must match GM_MAXRUN emitted below */              /* run weights are Q10 of the peak |g| of the band */

static int32_t *buf, *tmp;
static double *g;            /* SH x W response, normalised by AMP */

/* place a unit impulse at band coefficient (rr, cc) and read the response */
static void impulse(const omc_band_t *B, int rr, int cc)
{
    memset(buf, 0, sizeof(int32_t) * (size_t)W * SH);
    buf[(size_t)(B->r0 + rr) * W + (B->c0 + cc)] = AMP;
    omc_slice_inv(buf, W, SH, tmp);
    for (size_t i = 0; i < (size_t)W * SH; i++) g[i] = (double)buf[i] / AMP;
}

int main(void)
{
    omc_band_t B[OMC_NBANDS];
    omc_band_layout(W, SH, B);
    buf = calloc((size_t)W * SH, sizeof(int32_t));
    tmp = calloc((size_t)W * SH + 4 * W, sizeof(int32_t));
    g   = calloc((size_t)W * SH, sizeof(double));

    printf("/* GENERATED by repro/gen_gm_basis.c -- do not edit.\n"
           " * Sign/magnitude runs of the separable synthesis basis of each band,\n"
           " * measured by impulse response through omc_slice_inv().\n"
           " * See section 12.22 of docs/TEMPORAL_T5.md. */\n\n");

    /* first pass: find the support box and the run structure of each band */
    printf("#define GM_MAXRUN %d\n\n", GM_MAXRUN_C);
    printf("typedef struct {\n"
           "    int16_t off;      /* first pixel of the run, relative to the\n"
           "                       * coefficient's nominal position idx*stride */\n"
           "    int16_t len;      /* pixels in the run */\n"
           "    int16_t w;        /* mean |g| over the run, Q10 of the band peak */\n"
           "    int16_t sgn;      /* +1 or -1 */\n"
           "} gm_run_t;\n\n");
    printf("typedef struct {\n"
           "    int8_t   ny, nx;  /* runs in each direction */\n"
           "    int8_t   s0;      /* sign correction, see gen_gm_basis.c */\n"
           "    int16_t  sy0, sy1;/* FULL support box in rows, relative to */\n"
           "    int16_t  sx0, sx1;/* (row*vd, col*hd), dropped runs included. */\n"
           "    int16_t  vd, hd;  /* pixels per coefficient, vertical/horizontal */\n"
           "    gm_run_t y[GM_MAXRUN], x[GM_MAXRUN];\n"
           "} gm_basis_t;\n\n");
    printf("static const gm_basis_t GM_BASIS[OMC_NBANDS] = {\n");

    for (int k = 0; k < OMC_NBANDS; k++) {
        const omc_band_t *b = &B[k];
        int vd = SH / b->h, hd = W / b->w;
        int rr = b->h / 2, cc = b->w / 2;
        impulse(b, rr, cc);
        /* support box */
        int y0 = SH, y1 = -1, x0 = W, x1 = -1;
        double peak = 0;
        for (int y = 0; y < SH; y++)
            for (int x = 0; x < W; x++) {
                double v = g[(size_t)y * W + x];
                double a = v < 0 ? -v : v;
                if (a > peak) peak = a;
            }
        double eps = peak * 1e-6;
        for (int y = 0; y < SH; y++)
            for (int x = 0; x < W; x++) {
                double a = g[(size_t)y * W + x];
                if (a < 0) a = -a;
                if (a > eps) {
                    if (y < y0) y0 = y;
                if (y > y1) y1 = y;
                    if (x < x0) x0 = x;
                    if (x > x1) x1 = x;
                }
            }
        /* the peak cell, used to factor the separable basis */
        int py = y0, px = x0; double pv = 0;
        for (int y = y0; y <= y1; y++)
            for (int x = x0; x <= x1; x++) {
                double a = g[(size_t)y * W + x];
                if (a < 0) a = -a;
                if (a > pv) { pv = a; py = y; px = x; }
            }
        /* gy[j] = g(j, px), gx[i] = g(py, i), and
         * sign(g(j,i)) = sign(gy[j]) * sign(gx[i]) * sign(g(py,px)) */
        int s0 = g[(size_t)py * W + px] < 0 ? -1 : 1;
        fprintf(stderr, "band %d  vd=%d hd=%d  rows[%d..%d] cols[%d..%d]  "
                "peak %.6f at (%d,%d)\n", k, vd, hd, y0, y1, x0, x1, pv, py, px);

        /* --- runs --- */
        struct { int off, len, sgn; double sum; } ry[64], rx[64];
        int ny = 0, nx = 0;
        double gymax = 0, gxmax = 0;
        for (int y = y0; y <= y1; y++) { double a = g[(size_t)y*W+px]; if (a<0) a=-a; if (a>gymax) gymax=a; }
        for (int x = x0; x <= x1; x++) { double a = g[(size_t)py*W+x]; if (a<0) a=-a; if (a>gxmax) gxmax=a; }
        for (int y = y0; y <= y1; y++) {
            double v = g[(size_t)y * W + px];
            int s = v < 0 ? -1 : 1;
            if (ny && ry[ny-1].sgn == s && ry[ny-1].off + ry[ny-1].len == y) {
                ry[ny-1].len++; ry[ny-1].sum += v < 0 ? -v : v;
            } else { ry[ny].off = y; ry[ny].len = 1; ry[ny].sgn = s;
                     ry[ny].sum = v < 0 ? -v : v; ny++; }
        }
        for (int x = x0; x <= x1; x++) {
            double v = g[(size_t)py * W + x];
            int s = v < 0 ? -1 : 1;
            if (nx && rx[nx-1].sgn == s && rx[nx-1].off + rx[nx-1].len == x) {
                rx[nx-1].len++; rx[nx-1].sum += v < 0 ? -v : v;
            } else { rx[nx].off = x; rx[nx].len = 1; rx[nx].sgn = s;
                     rx[nx].sum = v < 0 ? -v : v; nx++; }
        }
        fprintf(stderr, "   runs: ny=%d nx=%d\n", ny, nx);
        /* A run whose mean |g| rounds to zero at Q10 cannot change the sign of
         * any score it takes part in, so it is dropped: it would only cost the
         * repair four summed-area lookups to add nothing.  Dropping one leaves
         * a gap in the support, which is correct -- a gap contributes nothing. */
        int wy[64], wx[64], ky = 0, kx = 0;
        for (int i = 0; i < ny; i++) {
            wy[i] = (int)(ry[i].sum / ry[i].len / gymax * WQ + 0.5);
            if (wy[i]) ky++;
        }
        for (int i = 0; i < nx; i++) {
            wx[i] = (int)(rx[i].sum / rx[i].len / gxmax * WQ + 0.5);
            if (wx[i]) kx++;
        }
        if (ky > GM_MAXRUN_C || kx > GM_MAXRUN_C) {
            fprintf(stderr, "band %d needs %d x %d runs, GM_MAXRUN is %d\n",
                    k, ky, kx, GM_MAXRUN_C);
            return 1;
        }
        printf("  { %d, %d, %d, %d, %d, %d, %d, %d, %d,\n    {", ky, kx, s0,
               y0 - rr * vd, y1 - rr * vd, x0 - cc * hd, x1 - cc * hd, vd, hd);
        for (int i = 0, o = 0; i < ny; i++) {
            if (!wy[i]) continue;
            printf("%s{%d,%d,%d,%d}", o++ ? "," : "", ry[i].off - rr * vd, ry[i].len,
                   wy[i], ry[i].sgn);
        }
        printf("},\n    {");
        for (int i = 0, o = 0; i < nx; i++) {
            if (!wx[i]) continue;
            printf("%s{%d,%d,%d,%d}", o++ ? "," : "", rx[i].off - cc * hd, rx[i].len,
                   wx[i], rx[i].sgn);
        }
        printf("} },\n");
        /* the support box, for the edge fall-through: the repair must not apply
         * an interior sign table to a coefficient whose basis is reshaped by the
         * symmetric extension at a slice or plane boundary */
        fprintf(stderr, "   support rows [%d..%d] cols [%d..%d] relative to "
                "(row*%d, col*%d)\n", y0 - rr * vd, y1 - rr * vd,
                x0 - cc * hd, x1 - cc * hd, vd, hd);
    }
    printf("};\n");
    free(buf); free(tmp); free(g);
    return 0;
}
