"""Generate the static tANS symbol-distribution tables (src/tables.c / include/tables.h).

The tables are part of the normative OMC-1 v1.0 specification: a fixed family of 16
category-symbol distributions covering zero-probabilities from 5% to 99% in two
decay classes. The encoder picks the best table per (band, context) by measured
histogram cost; the id is signaled in the slice header. All tables give every
symbol a nonzero count so any symbol is encodable with any table.

Alphabet: 16 symbols = magnitude category 0..15 (0 = zero coefficient,
cat k>=1 means |q| has k significant bits; (k-1) LSB bits + 1 sign bit raw).

tANS table size L = 1024 (2^10).
"""

import numpy as np

L = 1024
NSYM = 16
P0S = [0.05, 0.30, 0.50, 0.70, 0.82, 0.90, 0.95, 0.985]
DECAYS = [0.42, 0.68]


def make_counts(p0, decay):
    p = np.zeros(NSYM)
    p[0] = p0
    rest = 1.0 - p0
    w = decay ** np.arange(NSYM - 1)
    p[1:] = rest * w / w.sum()
    # normalize to L with a floor of 1 per symbol
    c = np.maximum(1, np.round(p * L)).astype(int)
    # fix rounding drift on the largest entry
    c[np.argmax(c)] += L - c.sum()
    assert c.sum() == L and (c >= 1).all()
    return c


def main():
    tables = [make_counts(p0, d) for d in DECAYS for p0 in P0S]
    with open("include/tables.h", "w") as f:
        f.write("/* Generated by harness/gen_tables.py - OMC-1 v1.0 normative tANS tables */\n")
        f.write("#ifndef OMC1_TABLES_H\n#define OMC1_TABLES_H\n#include <stdint.h>\n")
        f.write(f"#define OMC_TANS_L {L}\n#define OMC_TANS_LBITS 10\n")
        f.write(f"#define OMC_NSYM {NSYM}\n#define OMC_NTABLES {len(tables)}\n")
        f.write("extern const uint16_t omc_tans_counts[OMC_NTABLES][OMC_NSYM];\n")
        f.write("extern const uint16_t omc_tans_cost64[OMC_NTABLES][OMC_NSYM];\n")
        f.write("#endif\n")
    with open("src/tables.c", "w") as f:
        f.write("/* Generated by harness/gen_tables.py - OMC-1 v1.0 normative tANS tables */\n")
        f.write('#include "tables.h"\n\n')
        f.write("const uint16_t omc_tans_counts[OMC_NTABLES][OMC_NSYM] = {\n")
        for c in tables:
            f.write("  {" + ",".join(str(x) for x in c) + "},\n")
        f.write("};\n\n")
        # cost in 1/64 bit units: -log2(c/L) * 64, rounded
        f.write("const uint16_t omc_tans_cost64[OMC_NTABLES][OMC_NSYM] = {\n")
        for c in tables:
            cost = np.round(-np.log2(c / L) * 64).astype(int)
            cost = np.maximum(1, cost)
            f.write("  {" + ",".join(str(x) for x in cost) + "},\n")
        f.write("};\n")
    print(f"wrote {len(tables)} tables")


if __name__ == "__main__":
    main()
