"""Retrain the 16 normative tANS tables on measured symbol statistics.

Collects per-(plane, band, ctx) magnitude-category histograms from the corpus
(via the numpy mirror of the codec datapath in proto.py) across the operating
Q range, then Lloyd-clusters them under cross-entropy into 16 tables.
Writes include/tables.h + src/tables.c via the same emitter as gen_tables.py.

Run: python3 harness/train_tables.py   (from repo root: paths are relative)
"""

import json

import numpy as np

from common import MASTERS_DIR, SEQUENCES, read_yuv
from proto import slice_fwd2, quant

L = 1024
NSYM = 16

OFF = {
    0: [-4, -3, -3, -2, -1, -1, 0, 0, 0, 1],
    1: [-4, -3, -2, -1, 0, 0, 1, 1, 1, 2],
    2: [-4, -3, -2, -1, 0, 0, 1, 1, 1, 2],
}
LL_CAP = 2


def band_hist(qb, dpcm_row_w=None):
    """(2, NSYM) histogram with left-significance context, matching the C codec."""
    if dpcm_row_w is not None:
        v = np.diff(qb, axis=-1, prepend=0)
    else:
        v = qb
    flat = v.ravel()
    a = np.abs(flat).astype(np.int64)
    cat = np.zeros(len(flat), dtype=np.int64)
    nz = a > 0
    cat[nz] = np.searchsorted(2 ** np.arange(1, 17, dtype=np.int64), a[nz], side="right") + 1
    np.clip(cat, 0, NSYM - 1, out=cat)
    prevnz = np.concatenate([[0], nz[:-1].astype(np.int64)])
    hists = np.zeros((2, NSYM), dtype=np.int64)
    for c in (0, 1):
        m = prevnz == c
        hists[c] = np.bincount(cat[m], minlength=NSYM)[:NSYM]
    return hists


def collect():
    mani = json.load(open(MASTERS_DIR + "/manifest.json"))
    hists = []
    for name in SEQUENCES:
        w, h = mani[name]["w"], mani[name]["h"]
        fr = read_yuv(f"{MASTERS_DIR}/{name}_422_10.yuv", w, h, w // 2, nframes=1)[0]
        for Q in (3, 4, 5, 6):
            for p, plane in enumerate(fr):
                pw = plane.shape[1]
                acc = {}
                for y0 in range(0, h, 16):
                    tile = plane[y0:y0 + 16].astype(np.int32) - 512
                    bands = slice_fwd2(tile)
                    for b in range(10):
                        s = max(0, min(15, Q + OFF[p][b]))
                        if b == 0:
                            s = min(s, LL_CAP)
                        qb = quant(bands[b], s)
                        hh = band_hist(qb, dpcm_row_w=bands[b].shape[1] if b == 0 else None)
                        key = (b,)
                        acc[key] = acc.get(key, 0) + hh
                for hh in acc.values():
                    hists.append(hh[0])
                    hists.append(hh[1])
        print(f"collected {name}", flush=True)
    return [h for h in hists if h.sum() > 0]


def cross_entropy_bits(hist, probs):
    return float(-(hist * np.log2(probs)).sum())


def lloyd(hists, k=16, iters=12):
    hists = [h.astype(np.float64) for h in hists]
    # init: spread by zero-fraction quantiles
    zf = np.array([h[0] / h.sum() for h in hists])
    order = np.argsort(zf)
    cents = []
    for i in range(k):
        idx = order[int((i + 0.5) * len(order) / k)]
        cents.append(hists[idx] / hists[idx].sum())
    cents = np.array(cents)
    for it in range(iters):
        # assignment
        assign = []
        total = 0.0
        sums = np.zeros((k, NSYM))
        for h in hists:
            costs = [cross_entropy_bits(h, np.maximum(c, 1e-12)) for c in cents]
            j = int(np.argmin(costs))
            assign.append(j)
            total += costs[j]
            sums[j] += h
        for j in range(k):
            if sums[j].sum() > 0:
                cents[j] = sums[j] / sums[j].sum()
        print(f"iter {it}: total bits {total/8/1024:.1f} KB", flush=True)
    return cents


def emit(cents):
    tables = []
    for p in cents:
        c = np.maximum(1, np.round(p * L)).astype(int)
        c[np.argmax(c)] += L - c.sum()
        assert c.sum() == L and (c >= 1).all()
        tables.append(c)
    with open("include/tables.h", "w") as f:
        f.write("/* Generated by harness/train_tables.py - OMC-1 v1.0 normative tANS tables */\n")
        f.write("#ifndef OMC1_TABLES_H\n#define OMC1_TABLES_H\n#include <stdint.h>\n")
        f.write(f"#define OMC_TANS_L {L}\n#define OMC_TANS_LBITS 10\n")
        f.write(f"#define OMC_NSYM {NSYM}\n#define OMC_NTABLES {len(tables)}\n")
        f.write("extern const uint16_t omc_tans_counts[OMC_NTABLES][OMC_NSYM];\n")
        f.write("extern const uint16_t omc_tans_cost64[OMC_NTABLES][OMC_NSYM];\n")
        f.write("#endif\n")
    with open("src/tables.c", "w") as f:
        f.write("/* Generated by harness/train_tables.py - OMC-1 v1.0 normative tANS tables */\n")
        f.write('#include "tables.h"\n\n')
        f.write("const uint16_t omc_tans_counts[OMC_NTABLES][OMC_NSYM] = {\n")
        for c in tables:
            f.write("  {" + ",".join(str(x) for x in c) + "},\n")
        f.write("};\n\n")
        f.write("const uint16_t omc_tans_cost64[OMC_NTABLES][OMC_NSYM] = {\n")
        for c in tables:
            cost = np.maximum(1, np.round(-np.log2(np.array(c) / L) * 64).astype(int))
            f.write("  {" + ",".join(str(x) for x in cost) + "},\n")
        f.write("};\n")
    print(f"wrote {len(tables)} trained tables")


if __name__ == "__main__":
    h = collect()
    print(f"{len(h)} histograms")
    c = lloyd(h)
    emit(c)
