#!/usr/bin/env python3
"""Train the v4.4 tANS tables: 4 groups x 16 magnitude-contexts x 16 symbols.

Replicates the codec's runtime behavior (encoder picks the best group per
(slice, band) via measured cost), so training = Lloyd clustering of per-record
context-histograms into 4 groups under total cross-entropy.
Emits C arrays for src/tables.c (counts sum to 1024, min 1, cost64 tables).
Training clips only (held-out discipline maintained).
"""
import os
import numpy as np

W_ = os.path.dirname(os.path.abspath(__file__))
TRAIN = ["beach", "aerial", "couch", "soccer", "heli", "graincell", "mms", "cow"]
NCTX, NSYM, K, L = 16, 16, 8, 1024

CATB = (2 ** np.arange(1, 17)).astype(np.int64)
def cat_of(a): return np.searchsorted(CATB, a, side="right").astype(np.int64) + (a > 0)
def q2(a): return np.clip(np.where(a == 0, 0, np.where(a == 1, 1, np.where(a <= 3, 2, 3))), 0, 3)

def load(clip):
    p = os.path.join(W_, f"dump2_{clip}.bin")
    buf = np.fromfile(p, dtype=np.uint8)
    off = 0
    while off + 32 <= len(buf):
        hdr = buf[off:off+32].view(np.int32)
        frame, sl, plane, band, shift, w, n, mode = [int(x) for x in hdr]
        off += 32
        if n <= 0 or w <= 0 or off + 4*n > len(buf): break
        v = buf[off:off+2*n].view(np.int16).astype(np.int64); off += 4*n
        h = n // w
        yield band, v[:h*w].reshape(h, w)

def rec_hist(v):
    a = np.abs(v)
    cat = np.minimum(cat_of(a), NSYM - 1)
    l = np.zeros_like(a); l[:, 1:] = a[:, :-1]
    up = np.zeros_like(a); up[1:, :] = a[:-1, :]
    ctx = q2(l) * 4 + q2(up)
    h = np.zeros((NCTX, NSYM), dtype=np.int64)
    np.add.at(h, (ctx.ravel(), cat.ravel()), 1)
    return h

def main():
    hists = []
    for c in TRAIN:
        for band, v in load(c):
            if v.size >= 64:
                hists.append(rec_hist(v))
    H = np.stack(hists)  # [R, NCTX, NSYM]
    print(f"{len(H)} training records", flush=True)
    # init 4 groups by total record energy quartiles (proxy for band tier)
    energy = (H * np.arange(NSYM)).sum(axis=(1, 2)) / np.maximum(H.sum(axis=(1, 2)), 1)
    order = np.argsort(energy)
    assign = np.zeros(len(H), dtype=np.int64)
    for k in range(K):
        assign[order[k * len(H) // K:(k + 1) * len(H) // K]] = k
    for it in range(12):
        # group tables from assignments
        tabs = np.zeros((K, NCTX, NSYM))
        for k in range(K):
            g = H[assign == k].sum(axis=0) + 1
            tabs[k] = -np.log2(g / g.sum(axis=1, keepdims=True))
        # reassign by cost
        costs = np.einsum("rcs,kcs->rk", H, tabs)
        new = costs.argmin(axis=1)
        moved = int((new != assign).sum())
        assign = new
        print(f"iter {it}: moved {moved}", flush=True)
        if moved == 0: break
    # final counts, normalized to 1024 with min 1 (exact sum fixup)
    counts = np.zeros((K, NCTX, NSYM), dtype=np.int64)
    for k in range(K):
        g = H[assign == k].sum(axis=0) + 1
        for c in range(NCTX):
            row = g[c].astype(np.float64)
            cc = np.maximum(np.round(row / row.sum() * L), 1).astype(np.int64)
            while cc.sum() > L:
                cc[cc.argmax()] -= 1
            while cc.sum() < L:
                cc[cc.argmax()] += 1
            counts[k, c] = cc
    # emit C
    with open(os.path.join(W_, "tables_v4.c.inc"), "w") as f:
        f.write("/* Generated by work/train_tables_v4.py - v4.4 normative tANS tables\n"
                " * (4 groups x 16 magnitude-contexts x 16 symbols; trained on the\n"
                " * beach/aerial/couch/soccer masters, validated held-out). */\n")
        f.write("const uint16_t omc_tans_counts_v4[OMC_NTABLES_V4][OMC_NCTX_V4][OMC_NSYM] = {\n")
        for k in range(K):
            f.write(" {\n")
            for c in range(NCTX):
                f.write("  {" + ",".join(str(int(x)) for x in counts[k, c]) + "},\n")
            f.write(" },\n")
        f.write("};\n")
        f.write("const uint16_t omc_tans_cost64_v4[OMC_NTABLES_V4][OMC_NCTX_V4][OMC_NSYM] = {\n")
        for k in range(K):
            f.write(" {\n")
            for c in range(NCTX):
                p = counts[k, c] / counts[k, c].sum()
                cost = np.minimum(np.round(-np.log2(p) * 64), 65535).astype(np.int64)
                f.write("  {" + ",".join(str(int(x)) for x in cost) + "},\n")
            f.write(" },\n")
        f.write("};\n")
    print("wrote tables_v4.c.inc", flush=True)

if __name__ == "__main__":
    main()
