"""Train OMC v2 tANS table GROUPS: 16 groups x 4 contexts x 16 symbols.

v2 context model: ctx = sig(left) + 2*sig(above) in {0..3}, computed on the
coded value stream of each band (post-DPCM for LL). A band's slice header
carries ONE 4-bit group id; the group provides all four context tables.

Training: per (sequence, Q, plane, band) collect the 4 context histograms,
Lloyd-cluster the 4-tuples under total cross-entropy into 16 groups, emit
include/tables.h + src/tables.c.
"""

import json

import numpy as np

from common import MASTERS_DIR, SEQUENCES, read_yuv
from proto import slice_fwd2, quant

L = 1024
NSYM = 16
NCTX = 4
K = 16

OFF = [-4, -3, -3, -2, -1, -1, 0, 0, 0, 1]  # balanced ladder, all planes
LL_CAP = 2


def band_hists(qb, dpcm=False):
    v = np.diff(qb, axis=-1, prepend=0) if dpcm else qb
    a = np.abs(v).astype(np.int64)
    cat = np.zeros(a.shape, dtype=np.int64)
    nz = a > 0
    cat[nz] = np.searchsorted(2 ** np.arange(1, 17, dtype=np.int64), a[nz], side="right") + 1
    np.clip(cat, 0, NSYM - 1, out=cat)
    sig = (cat > 0).astype(np.int64)
    left = np.zeros_like(sig); left[:, 1:] = sig[:, :-1]
    above = np.zeros_like(sig); above[1:, :] = sig[:-1, :]
    ctx = left + 2 * above
    out = np.zeros((NCTX, NSYM), dtype=np.int64)
    for c in range(NCTX):
        m = ctx == c
        out[c] = np.bincount(cat[m], minlength=NSYM)[:NSYM]
    return out


def collect():
    mani = json.load(open(MASTERS_DIR + "/manifest.json"))
    tuples = []
    for name in SEQUENCES:
        w, h = mani[name]["w"], mani[name]["h"]
        fr = read_yuv(f"{MASTERS_DIR}/{name}_422_10.yuv", w, h, w // 2, nframes=1)[0]
        for Q in (3, 4, 5, 6):
            for p, plane in enumerate(fr):
                acc = [np.zeros((NCTX, NSYM), dtype=np.int64) for _ in range(10)]
                for y0 in range(0, h, 16):
                    tile = plane[y0:y0 + 16].astype(np.int32) - 512
                    bands = slice_fwd2(tile)
                    for b in range(10):
                        s = max(0, min(15, Q + OFF[b]))
                        if b == 0:
                            s = min(s, LL_CAP)
                        acc[b] += band_hists(quant(bands[b], s), dpcm=(b == 0))
                for b in range(10):
                    if acc[b].sum() > 0:
                        tuples.append(acc[b].astype(np.float64))
        print("collected", name, flush=True)
    return tuples


def cost(tup, cents):
    c = 0.0
    for x in range(NCTX):
        h = tup[x]
        n = h.sum()
        if n == 0:
            continue
        c += -(h * np.log2(np.maximum(cents[x], 1e-12))).sum()
    return c


def lloyd(tuples, iters=12):
    # init by zero-fraction quantiles of ctx0
    zf = np.array([t[0][0] / max(1, t[0].sum()) for t in tuples])
    order = np.argsort(zf)
    cents = []
    for i in range(K):
        t = tuples[order[int((i + 0.5) * len(order) / K)]]
        cents.append(np.array([r / max(1, r.sum()) for r in t]))
    cents = np.array(cents)
    for it in range(iters):
        sums = np.zeros((K, NCTX, NSYM))
        total = 0.0
        for t in tuples:
            costs = [cost(t, cents[j]) for j in range(K)]
            j = int(np.argmin(costs))
            total += costs[j]
            sums[j] += t
        for j in range(K):
            for x in range(NCTX):
                if sums[j][x].sum() > 0:
                    cents[j][x] = sums[j][x] / sums[j][x].sum()
        print(f"iter {it}: {total/8/1024:.0f} KB", flush=True)
    return cents


def emit(cents):
    with open("include/tables.h", "w") as f:
        f.write("/* Generated by harness/train_tables2.py - OMC v2 normative tANS table groups */\n")
        f.write("#ifndef OMC1_TABLES_H\n#define OMC1_TABLES_H\n#include <stdint.h>\n")
        f.write(f"#define OMC_TANS_L {L}\n#define OMC_TANS_LBITS 10\n")
        f.write(f"#define OMC_NSYM {NSYM}\n#define OMC_NCTX {NCTX}\n#define OMC_NTABLES {K}\n")
        f.write("extern const uint16_t omc_tans_counts[OMC_NTABLES][OMC_NCTX][OMC_NSYM];\n")
        f.write("extern const uint16_t omc_tans_cost64[OMC_NTABLES][OMC_NCTX][OMC_NSYM];\n")
        f.write("#endif\n")
    with open("src/tables.c", "w") as f:
        f.write("/* Generated by harness/train_tables2.py - OMC v2 normative tANS table groups */\n")
        f.write('#include "tables.h"\n\n')
        f.write("const uint16_t omc_tans_counts[OMC_NTABLES][OMC_NCTX][OMC_NSYM] = {\n")
        for g in cents:
            f.write(" {\n")
            for row in g:
                c = np.maximum(1, np.round(row * L)).astype(int)
                c[np.argmax(c)] += L - c.sum()
                assert c.sum() == L and (c >= 1).all()
                f.write("  {" + ",".join(str(x) for x in c) + "},\n")
            f.write(" },\n")
        f.write("};\n\n")
        f.write("const uint16_t omc_tans_cost64[OMC_NTABLES][OMC_NCTX][OMC_NSYM] = {\n")
        for g in cents:
            f.write(" {\n")
            for row in g:
                c = np.maximum(1, np.round(row * L)).astype(int)
                c[np.argmax(c)] += L - c.sum()
                cost64 = np.maximum(1, np.round(-np.log2(c / L) * 64).astype(int))
                f.write("  {" + ",".join(str(x) for x in cost64) + "},\n")
            f.write(" },\n")
        f.write("};\n")
    print("wrote", K, "groups")


if __name__ == "__main__":
    t = collect()
    print(len(t), "band tuples")
    c = lloyd(t)
    emit(c)
